spring:
  mail:
    host: smtp.163.com
    username: 18317153556@163.com
    password: Cai199412
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  freemarker:
    template-loader-path: classpath:/static/template/
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
#thymeleaf
  thymeleaf:
    prefix: classpath:/static/template/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
